type: Heimdall.fe.BinningFe

args:
  embedding_parameters:
    type: Heimdall.utils.ScGPTCategoryValueEncoder 
    args:
      num_embeddings: ${fe.args.num_bins}
      embedding_dim: ${fe.args.d_embedding}
  num_bins: 10
  d_embedding: ${model.args.d_model}
