type: Heimdall.fe.NonzeroIdentityFe
name: Heimdall.fe.scfound

args:
  embedding_parameters:
    type: Heimdall.embedding.AutoDiscretizationEmbedding2
    args:
      dim: ${model.args.d_model} # Replace later
      bin_num: 100
      bin_alpha: 1
      mask_token_id: null
      pad_token_id: null
  d_embedding: ${model.args.d_model}
  drop_zeros: True