name: "SortingFe"

args:
  embedding_filepath: null
  num_embeddings: null # TODO: how to make number of genes? Maybe use `null` to indicate this? Or at least, individual Fes can ignore `num_embeddings` if they want
  d_embedding: 128 #
