type: Heimdall.fe.SortingFe

args:
  embedding_parameters:
    type: Heimdall.embedding.FlexibleTypeEmbedding
    args:
      num_embeddings: "max_seq_length"
      embedding_dim: ${fe.args.d_embedding}
  d_embedding: ${model.args.d_model}
  drop_zeros: True
