type: Heimdall.fe.SortingFe

args:
  torch_parameters:
    type: torch.nn.Embedding
    args:
      num_embeddings: "max_seq_length"
      embedding_dim: ${fe.args.d_embedding}
  d_embedding: ${model.args.d_model}
