type: Heimdall.models.HeimdallTransformer
name: transformer_dropout
args:
  d_model: 64
  pos_enc: BERT
  num_encoder_layers: 2
  nhead: 2
  hidden_act: gelu
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  use_flash_attn: false
  pooling: cls_pooling # or "mean_pooling"
