type: Heimdall.models.HeimdallTransformer
name: transformer
args:
  d_model: 64
  pos_enc: BERT
  num_encoder_layers: 1
  nhead: 2
  hidden_act: gelu
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  use_flash_attn: True
  pooling: cls_pooling # or "mean_pooling"
