name: "ESM2Fg"

args:
  output_type: "ids" ## specify whether the output is numerical IDs like 1,2,3,4 or a vector
  embedding_filepath: ${data_path}/pretrained_embeddings/ESM2/protein_map_human_ensembl.pt
  d_embedding: 512 # TODO: get right embedding dimensionality
