# @package _global_

data_path: data
ensembl_dir: ${data_path}
entity: Heimdall
# cache_preprocessed_dataset_dir: null
cache_preprocessed_dataset_dir: heimdall_preprocessed


# data_path: '/work/magroup/scllm/datasets'
# ensembl_dir: '/work/magroup/shared/Heimdall/data/gene_mapping'
# cache_preprocessed_dataset_dir: '/work/magroup/shared/Heimdall/preprocessed_data'  # dir to save preprocessed dataset, do not cache if set to null
# entity: 'Heimdall'
