type: Heimdall.fg.Gene2VecFg

args:
  embedding_parameters:
    type: Heimdall.embedding.FlexibleTypeEmbedding
    constructor: from_pretrained
    args:
      embeddings: gene_embeddings
  embedding_filepath: ${data_path}/pca_embeds/new_gene2vec_embeds.pt
  d_embedding: ${model.args.d_model}
  frozen: true
