type: Heimdall.fc.DummyFc

args:
  max_input_length: 2048
  embedding_parameters:
    type: torch.nn.Module  # Should throw an error if called
  tailor_config:
    type: Heimdall.tailor.Tailor  # Should throw an error if called
  order_config:
    type: Heimdall.order.Order  # Should throw an error if called
  reduce_config:
    type: Heimdall.reduce.Reduce  # Should throw an error if called
