args:
  task_type: binary
  interaction_type: _all_
  splits:
    type: predefined
    keys_:
      train: train
      val: val
      test: test
  metrics: [Accuracy]
  shuffle: true
  batchsize: 32
  epochs: 10
  reduction:
    type: Heimdall.models.SumReducer
  dataset_config:
    type: Heimdall.datasets.PairedInstanceDataset
  head_config:
    type: Heimdall.models.LinearCellPredHead
    args:
