## trainer details
accelerator: cuda
precision: 32-true
random_seed: ${seed}

per_device_batch_size: 64
accumulate_grad_batches: 1
grad_norm_clip: 1.0

fastdev: false  # if set to true, then only train/evel/test on the first batch
