type: Heimdall.task.Task

args:
  task_type: mlm
  label_obsm_name: mlm
  metrics: [Accuracy, MatthewsCorrCoef]
  train_split: 0.95
  shuffle: true
  batchsize: 512
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.PartitionedDataset
    # args:
    #   mask_ratio: 0.15
  head_config:
    type: Heimdall.models.LinearSeqPredHead
    args:
  cell_rep_config:
    type: Heimdall.cell_representations.PartitionedCellRepresentation
  loss_config:
    type: Heimdall.losses.FlattenCrossEntropyLoss
