type: Heimdall.task.PairedInstanceTask

args:
  task_type: multiclass
  interaction_type: task_ko
  splits:
    type: predefined
    keys_:
      train: train
      val: val
      test: test
  metrics: [Accuracy, MatthewsCorrCoef, F1Score]
  top_k: [1, 5, 10, 15, 20]
  track_metric: MatthewsCorrCoef
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
  reducer_config:
    type: Heimdall.models.SymmetricConcatReducer
  dataset_config:
    type: Heimdall.datasets.PairedInstanceDataset
  head_config:
    type: Heimdall.models.LinearCellPredHead
    args:
  loss_config:
    type: Heimdall.losses.FlattenCrossEntropyLoss

cell_rep_config:
  type: Heimdall.cell_representations.CellRepresentation
