type: Heimdall.fg.ESM2Fg

args:
  embedding_parameters:
    type: Heimdall.utils.FlexibleTypeEmbedding
    constructor: from_pretrained
    args:
      embeddings: "gene_embeddings"
  embedding_filepath: ${data_path}/pretrained_embeddings/ESM2/protein_map_human_ensembl.pt
  d_embedding: ${model.args.d_model}
