type: Heimdall.fg.ESM2Fg

args:
  embedding_parameters:
    type: Heimdall.embedding.FlexibleTypeEmbeddingAndProjection
    args:
      embeddings: "gene_embeddings"
      d_model: ${model.args.d_model}
  embedding_filepath: ${data_path}/pretrained_embeddings/ESM2/protein_map_human_ensembl.pt
  d_embedding: 5120
  frozen: False
