type: Heimdall.fg.Gene2VecFg

args:
  embedding_parameters:
    type: Heimdall.embedding.FlexibleTypeEmbeddingAndProjection
    args:
      embeddings: "gene_embeddings"
      d_model: ${model.args.d_model}
  embedding_filepath: ${data_path}/pretrained_embeddings/gene2vec/gene2vec_genes.txt
  d_embedding: 200
  frozen: False
