name: "IdentityFg"
type: Heimdall.fg.IdentityFg
args:
  embedding_parameters:
    type: torch.nn.Embedding
    args:
      num_embeddings: "vocab_size"
      embedding_dim: ${fg.args.d_embedding}
  d_embedding: ${model.args.d_model}
