type: Heimdall.fg.GenePTFg

args:
  embedding_parameters:
    type: Heimdall.embedding.FlexibleTypeEmbedding
    constructor: from_pretrained
    args:
      embeddings: "gene_embeddings"
  embedding_filepath: ${data_path}/pca_embeds/new_genept_embeds.pt
  d_embedding: ${model.args.d_model}
  frozen: True
