## trainer details
type: Heimdall.trainer.HeimdallTrainer

args:
  random_seed: ${seed}
  accumulate_grad_batches: 1
  grad_norm_clip: 1.0
  fastdev: false  # if set to true, then only train/evel/test on the first batch
  skip_umaps: false

cpu: false
