# @package _global_
defaults:
  - lane

# cache_preprocessed_dataset_dir: /scratch/nzh/Heimdall/cache
cache_preprocessed_dataset_dir: null

# hydra:
#   job:
#     env_set:
#       WANDB_MODE: disabled
