# @package _global_

###
# Set the experiment parts you would like to import
####
defaults:
  - override /model: transformer # the chosen model
  - override /dataset: new_sctab # dataset for the relevant task
  - override /tasks: new_sctab_split # dataset for the relevant task
  - override /scheduler: cosine # contains scheduler
  - override /trainer: default # contains optimizer and trainer details
  - override /optimizer: AdamW
  - override /fc: geneformer
  - override /fg: identity
  - override /loss: CrossEntropyLoss

####
# Set the specific parameters you would like to change from the defaults
####


run_name: ${fg.type}_${fe.type}_${fc.type}_${model.type}_lr${optimizer.args.lr}_bz${tasks.args.batchsize}  ## what is set for WandB
work_dir: 'work_dir'  ## set your custom working directory

project_name: 'new_sctab_split5' #project name for WandB
tasks:
  args:
    splits:
      col: split5


seed: 55

optimizer:
  args:
    lr: 2e-3
