type: Heimdall.fc.UCEFc

args:
  max_input_length: 1200
  species: ${dataset.preprocess_args.species}
  num_metadata_tokens: 50
  embedding_parameters:
    type: Heimdall.embedding.GaussianInitEmbedding
    args:
      num_embeddings: ${fc.args.num_metadata_tokens}
      embedding_dim: ${fg.args.d_embedding}
