dataset_name: pretrain_10k

preprocess_args:
  data_path: /work/magroup/shared/Heimdall/pretrain_data/pretrain_subsets/subset_10k
  top_n_genes: false
  normalize: true
  log_1p: true
  scale_data: false
  species: human
