# @package _global_

###
# Set the experiment parts you would like to import
####
defaults:
  - override /model: expression_only # the chosen model
  - override /dataset: zheng68k # dataset for the relevant task
  - override /tasks: cell_type_annotation_baseline # dataset for the relevant task
  - override /scheduler: cosine # contains scheduler
  - override /trainer: default # contains optimizer and trainer details
  - override /optimizer: AdamW
  - override /fc: dummy
  - override /fe: dummy
  - override /fg: dummy
  - override /loss: CrossEntropyLoss


####
# Set the specific parameters you would like to change from the defaults
####


project_name: cta_zheng68k #project name for WandB
run_name: ${fg.type}_${fe.type}_${fc.type}_${model.type}_lr${optimizer.args.lr}_bz${tasks.args.batchsize}  ## what is set for WandB
work_dir: work_dir  ## set your custom working directory

seed: 55

optimizer:
  args:
    lr: 2e-3
