args:
  task_type: classification
  task_structure: paired
  interaction_type: _all_
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
  prediction_dim: 20
  rebalance: true
