args:
  task_type: multiclass
  label_col_name: class
  metrics:
    - Accuracy
    - MatthewsCorrCoef
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
  prediction_dim: 14
  dataset_config:
    type: Heimdall.datasets.SingleInstanceDataset
