args:
  task_type: binary
  interaction_type: Spatial_neigh
  splits:
    type: predefined
    keys_:
      train: Spatial_neigh_train_mask
      val: Spatial_neigh_val_mask
      test: Spatial_neigh_test_mask
  metrics:
    - Accuracy
  shuffle: true
  batchsize: 32
  epochs: 10
  rebalance: true
  reduction:
    type: Heimdall.models.SymmetricConcatReducer
  dataset_config:
    type: Heimdall.datasets.PairedInstanceDataset
  head_config:
    type: Heimdall.models.LinearCellPredHead
    args: null
