args:
  task_type: "classification"
  task_structure: "paired"
  interaction_type: 'Agt -> Agtr1a'
  # label_col_name: "class"
  metrics: ["Accuracy", "MatthewsCorrCoef"]
  train_split: 0.8
  shuffle: True
  batchsize: 32
  epochs: 10
  prediction_dim: 20
  rebalance: True

