args:
  task_type: binary
  interaction_type: _all_
  splits:
    type: predefined
    keys_:
      train: train
      val: val
      test: test
  metrics:
    - Accuracy
  shuffle: true
  batchsize: 32
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.PairedInstanceDataset
