args:
  task_type: mlm
  label_obsm_name: mlm
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: True
  batchsize: 32
  epochs: 20
  dataset_config:
    type: Heimdall.datasets.PartitionedDataset
    # args:
    #   mask_ratio: 0.15
  head_config:
    type: Heimdall.models.LinearSeqPredHead
    args: null
