args:
  task_type: classification
  task_structure: _deprecated_
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 20
  dataset_type: SeqMaskedPretrainDataset
  dataset_args:
    mask_ratio: 0.15
