args:
  task_type: mlm
  label_obsm_name: mlm
  metrics:
    - Accuracy
  train_split: 0.95
  shuffle: True
  batchsize: 512
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.PartitionedDataset
    # args:
    #   mask_ratio: 0.15
  head_config:
    type: Heimdall.models.LinearSeqPredHead
    args: null
  cell_rep_config:
    type: Heimdall.cell_representations.PartitionedCellRepresentation
