args:
  task_type: multiclass
  interaction_type: task_ko
  splits:
    type: predefined
    keys_:
      train: train
      val: val
      test: test
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.PairedInstanceDataset
