args:
  task_type: classification
  interaction_type: task_ko
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.PairedInstanceDataset
