args:
  task_type: "regression"
  label_col_name: "neighbor_density"
  metrics: ["MAE", "MSE"]
  train_split: 0.8
  shuffle: True
  batchsize: 32
  epochs: 10
  prediction_dim: 1
  dataset_config:
    type: Heimdall.datasets.SingleInstanceDataset
