args:
  task_type: classification
  task_structure: single
  label_col_name: celltype
  
  metrics:
    - Accuracy
    - MatthewsCorrCoef
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 20
  prediction_dim: 11
