

dataset_name: "cell_type_classification"

preprocess_args:
  data_path: "data/sc_sub_nick.h5ad"
  top_n_genes: 1000
  normalize: true
  log_1p: true
  scale_data: true

task_args:
  label_col_name: "class"
  metric_name: "MCC"
  train_split: 0.8
