dataset_name: "pancreas"

preprocess_args:
  data_path: "${data_path}/cell_type_annotation/processed/pancreas.h5ad"
  top_n_genes: 1024
  normalize: true
  log_1p: true
  scale_data: true
  species: 'human'
