dataset_name: "reverse_perturbation_prediction"

preprocess_args:
  data_path: "/work/magroup/shared/Heimdall/data/reverse_perturbation_prediction/processed/perturb_seq_norman_diff_ko_paired.h5ad"
  top_n_genes: 1000
  normalize: true
  log_1p: true
  scale_data: true
  species: 'human'

task_args:
  presplit: true
  paired: true
  label_train: "task_ko_tarin"
  label_val: "task_ko_val"
  label_test: "task_ko_test"
  metric_name: "MCC"
  batchsize: 32
  epochs: 10