dataset_name: scdrs

preprocess_args:
  data_path: ${data_path}/polygenic_disease_risk/processed/scdrs_tissue.h5ad
  top_n_genes: false
  normalize: true
  log_1p: true
  scale_data: false
  species: mouse
  get_medians: true
