dataset_name: "spatial_neighborhood"

preprocess_args:
  data_path: "${data_path}/spatial_neighborhood/spatial_dataset_minimal_intlabels.h5ad"
  top_n_genes: false
  normalize: true
  log_1p: true
  scale_data: false
  species: "mouse"
