dataset_name: "spatial_cta_merfish_starmapplus"

preprocess_args:
  data_path: "${data_path}/spatial_cta/spatial_cta_easy_hard_splits.h5ad"
  top_n_genes: false
  normalize: true
  log_1p: true
  scale_data: false
  species: "mouse"
