dataset_name: "spatial_neighbor_popular_cell_type"

preprocess_args:
  data_path: "/work/magroup/shared/Heimdall/data/spatial_neighborhood/spatial_dataset_minimal_intlabels.h5ad"
  normalize: true
  log_1p: true
  scale_data: true

task_args:
  label_col_name: "majority_neighbor_class"
  metric_name: "MCC"
  train_split: 0.8
  shuffle: True
  batchsize: 32
  epochs: 10
  prediction_dim: 22
