

dataset_name: "spatial_neighbor_proportion"

preprocess_args:
  data_path: "data/spatial_neighborhood/spatial_dataset.h5ad"
  normalize: true
  log_1p: true
  scale_data: true

task_args:
  label_col_name: "neighborhood_class_proportions"
  metric_name: "MCC"
  train_split: 0.8
  shuffle: True
  batchsize: 32
  epochs: 10
  prediction_dim: 20
