dataset_name: zheng68k

preprocess_args:
  data_path: ${data_path}/cell_type_annotation/processed/zheng68k.h5ad
  top_n_genes: 1000
  normalize: false
  log_1p: false
  scale_data: false
  species: human
