args:
  task_type: binary
  label_obsm_name: disease_classification
  splits:
    type: predefined
    keys_:
      train: train
      val: valid
      test: test
  metrics:
    - Accuracy
    - MatthewsCorrCoef
    - F1Score
  track_metric: MatthewsCorrCoef
  # train_split: 0.8
  # prediction_dim: 14
  shuffle: true
  batchsize: 32
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.SingleInstanceDataset
  head_config:
    type: Heimdall.models.ExpressionOnlyCellPredHead
    args: null
