args:
  task_type: multiclass
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 20
  dataset_config:
    type: Heimdall.datasets.SeqMaskedPretrainDataset
    args:
      mask_ratio: 0.15
  head_config:
    type: Heimdall.models.LinearSeqPredHead
    args: null
