args:
  task_type: multiclass
  label_col_name: majority_neighbor_class
  metrics:
    - Accuracy
    - MatthewsCorrCoef
    - F1Score
  track_metric: MatthewsCorrCoef
  train_split: 0.8
  shuffle: True
  batchsize: 32
  epochs: 10
  dataset_config:
    type: Heimdall.datasets.SingleInstanceDataset
  head_config:
    type: Heimdall.models.LinearCellPredHead
    args: null
